#include <stdio.h>
#include <stdlib.h>

int DisassembleSM83Op(unsigned char *buffer, int offset, FILE *file) {
    unsigned char *code = &buffer[offset];
    char decode[20];
    int opbytes = 1;
    sprintf(decode, "%04x ", offset);
    fputs(decode, file);
    switch(*code)
    {
        case 0x00: sprintf(decode, "NOP"); break;
        case 0x01: sprintf(decode, "LD BC, #$%02x%02x", code[2], code[1]); opbytes = 3; break;
        case 0x02: sprintf(decode, "LD (BC), A"); break;
        case 0x03: sprintf(decode, "INC BC"); break;
        case 0x04: sprintf(decode, "INC B"); break;
        case 0x05: sprintf(decode, "DEC B"); break;
        case 0x06: sprintf(decode, "LD B, #$%02x", code[1]); opbytes = 2; break;
        case 0x07: sprintf(decode, "RLCA"); break;
        case 0x08: sprintf(decode, "LD $%02x%02x, SP", code[2], code[1]); opbytes = 3; break;
        case 0x09: sprintf(decode, "ADD HL, BC"); break;
        case 0x0a: sprintf(decode, "LD A, (BC)"); break;
        case 0x0b: sprintf(decode, "DEC BC"); break;
        case 0x0c: sprintf(decode, "INC C"); break;
        case 0x0d: sprintf(decode, "DEC C"); break;
        case 0x0e: sprintf(decode, "LD C, #$%02x", code[1]); opbytes = 2; break;
        case 0x0f: sprintf(decode, "RRCA"); break;
        case 0x10: sprintf(decode, "STOP #$%02x", code[1]); opbytes = 2; break;
        case 0x11: sprintf(decode, "LD DE, #$%02x%02x", code[2], code[1]); opbytes = 3; break;
        case 0x12: sprintf(decode, "LD (DE), A"); break;
        case 0x13: sprintf(decode, "INC DE"); break;
        case 0x14: sprintf(decode, "INC D"); break;
        case 0x15: sprintf(decode, "DEC D"); break;
        case 0x16: sprintf(decode, "LD D, #$%02x%02x", code[2], code[1]); opbytes = 3; break;
        case 0x17: sprintf(decode, "RLA"); break;
        case 0x18: sprintf(decode, "JR $%02x", code[1]); opbytes = 2; break;
        case 0x19: sprintf(decode, "ADD HL, BC"); break;
        case 0X1a: sprintf(decode, "LD A, (DE)"); break;
        case 0X1b: sprintf(decode, "DEC DE"); break;
        case 0X1c: sprintf(decode, "INC E"); break;
        case 0X1d: sprintf(decode, "DEC E"); break;
        case 0X1e: sprintf(decode, "LD E, #$%02x", code[1]); opbytes = 2; break;
        case 0X1f: sprintf(decode, "RRA"); break;
        case 0X20: sprintf(decode, "JR NZ, $%02x", code[1]); opbytes = 2; break;
        case 0X21: sprintf(decode, "LD HL, #$%02x%02x", code[2], code[1]); opbytes = 3; break;
        case 0X22: sprintf(decode, "LD (HL+), A"); break;
        case 0X23: sprintf(decode, "INC HL"); break;
        case 0X24: sprintf(decode, "INC H"); break;
        case 0X25: sprintf(decode, "DEC H"); break;
        case 0X26: sprintf(decode, "LD H, #$%02x", code[1]); opbytes = 2; break;
        case 0X27: sprintf(decode, "DAA"); break;
        case 0X28: sprintf(decode, "JR Z, $%02x", code[1]); opbytes = 2; break;
        case 0X29: sprintf(decode, "ADD HL, HL"); break;
        case 0X2a: sprintf(decode, "LD A, (HL+)"); break;
        case 0X2b: sprintf(decode, "DEC HL"); break;
        case 0X2c: sprintf(decode, "INC L"); break;
        case 0X2d: sprintf(decode, "DEC L"); break;
        case 0X2e: sprintf(decode, "LD L, #$%02x", code[1]); opbytes = 2; break;
        case 0X2f: sprintf(decode, "CPL"); break;
        case 0X30: sprintf(decode, "JR NC, $%02x", code[1]); opbytes = 2; break;
        case 0X31: sprintf(decode, "LD SP, #$%02x%02x", code[2], code[1]); opbytes = 3; break;
        case 0X32: sprintf(decode, "LD (HL-), A"); break;
        case 0X33: sprintf(decode, "INC SP"); break;
        case 0X34: sprintf(decode, "INC (HL)"); break;
        case 0x35: sprintf(decode, "DEC (HL)"); break;
        case 0x36: sprintf(decode, "LD H, #$%02x", code[1]); opbytes = 2; break;
        case 0x37: sprintf(decode, "DDA"); break;
        case 0x38: sprintf(decode, "JR Z, $%02x", code[1]); opbytes = 2; break;
        case 0x39: sprintf(decode, "ADD HL, SP"); break;
        case 0x3a: sprintf(decode, "LD A, (HL-)"); break;
        case 0x3b: sprintf(decode, "DEC SP"); break;
        case 0x3c: sprintf(decode, "INC A"); break;
        case 0x3d: sprintf(decode, "DEC A"); break;
        case 0x3e: sprintf(decode, "LD A, #$%02x", code[1]); opbytes = 2; break;
        case 0x3f: sprintf(decode, "CCF"); break;
        case 0x40: sprintf(decode, "LD B, B"); break;
        case 0x41: sprintf(decode, "LD B, C"); break;
        case 0x42: sprintf(decode, "LD B, D"); break;
        case 0x43: sprintf(decode, "LD B, E"); break;
        case 0x44: sprintf(decode, "LD B, H"); break;
        case 0x45: sprintf(decode, "LD B, L"); break;
        case 0x46: sprintf(decode, "LD B, (HL)"); break;
        case 0x47: sprintf(decode, "LD B, A"); break;
        case 0x48: sprintf(decode, "LD C, B"); break;
        case 0x49: sprintf(decode, "LD C, C"); break;
        case 0x4a: sprintf(decode, "LD C, D"); break;
        case 0x4b: sprintf(decode, "LD C, E"); break;
        case 0x4c: sprintf(decode, "LD C, H"); break;
        case 0x4d: sprintf(decode, "LD C, L"); break;
        case 0x4e: sprintf(decode, "LD C, (HL)"); break;
        case 0x4f: sprintf(decode, "LD C, A"); break;
        case 0x50: sprintf(decode, "LD D, B"); break;
        case 0x51: sprintf(decode, "LD D, C"); break;
        case 0x52: sprintf(decode, "LD D, D"); break;
        case 0x53: sprintf(decode, "LD D, E"); break;
        case 0x54: sprintf(decode, "LD D, H"); break;
        case 0x55: sprintf(decode, "LD D, L"); break;
        case 0x56: sprintf(decode, "LD D, (HL)"); break;
        case 0x57: sprintf(decode, "LD D, A"); break;
        case 0x58: sprintf(decode, "LD E, B"); break;
        case 0x59: sprintf(decode, "LD E, C"); break;
        case 0x5a: sprintf(decode, "LD E, D"); break;
        case 0x5b: sprintf(decode, "LD E, E"); break;
        case 0x5c: sprintf(decode, "LD E, H"); break;
        case 0x5d: sprintf(decode, "LD E, L"); break;
        case 0x5e: sprintf(decode, "LD E, (HL)"); break;
        case 0x5f: sprintf(decode, "LD E, A"); break;
        case 0x60: sprintf(decode, "LD H, B"); break;
        case 0x61: sprintf(decode, "LD H, C"); break;
        case 0x62: sprintf(decode, "LD H, D"); break;
        case 0x63: sprintf(decode, "LD H, E"); break;
        case 0x64: sprintf(decode, "LD H, H"); break;
        case 0x65: sprintf(decode, "LD H, L"); break;
        case 0x66: sprintf(decode, "LD H, (HL)"); break;
        case 0x67: sprintf(decode, "LD H, A"); break;
        case 0x68: sprintf(decode, "LD L, B"); break;
        case 0x69: sprintf(decode, "LD L, C"); break;
        case 0x6a: sprintf(decode, "LD L, D"); break;
        case 0x6b: sprintf(decode, "LD L, E"); break;
        case 0x6c: sprintf(decode, "LD L, H"); break;
        case 0x6d: sprintf(decode, "LD L, L"); break;
        case 0x6e: sprintf(decode, "LD L, (HL)"); break;
        case 0x6f: sprintf(decode, "LD L, A"); break;
        case 0x70: sprintf(decode, "LD (HL), B"); break;
        case 0x71: sprintf(decode, "LD (HL), C"); break;
        case 0x72: sprintf(decode, "LD (HL), D"); break;
        case 0x73: sprintf(decode, "LD (HL), E"); break;
        case 0x74: sprintf(decode, "LD (HL), H"); break;
        case 0x75: sprintf(decode, "LD (HL), L"); break;
        case 0x76: sprintf(decode, "HALT"); break;
        case 0x77: sprintf(decode, "LD (HL), A"); break;
        case 0x78: sprintf(decode, "LD A, B"); break;
        case 0x79: sprintf(decode, "LD A, C"); break;
        case 0x7a: sprintf(decode, "LD A, D"); break;
        case 0x7b: sprintf(decode, "LD A, E"); break;
        case 0x7c: sprintf(decode, "LD A, H"); break;
        case 0x7d: sprintf(decode, "LD A, L"); break;
        case 0x7e: sprintf(decode, "LD A, (HL)"); break;
        case 0x7f: sprintf(decode, "LD A, A"); break;
        case 0x80: sprintf(decode, "ADD A, B"); break;
        case 0x81: sprintf(decode, "ADD A, C"); break;
        case 0x82: sprintf(decode, "ADD A, D"); break;
        case 0x83: sprintf(decode, "ADD A, E"); break;
        case 0x84: sprintf(decode, "ADD A, H"); break;
        case 0x85: sprintf(decode, "ADD A, L"); break;
        case 0x86: sprintf(decode, "ADD A, (HL)"); break;
        case 0x87: sprintf(decode, "ADD A, A"); break;
        case 0x88: sprintf(decode, "ADC A, B"); break;
        case 0x89: sprintf(decode, "ADC A, C"); break;
        case 0x8a: sprintf(decode, "ADC A, D"); break;
        case 0x8b: sprintf(decode, "ADC A, E"); break;
        case 0x8c: sprintf(decode, "ADC A, H"); break;
        case 0x8d: sprintf(decode, "ADC A, L"); break;
        case 0x8e: sprintf(decode, "ADC A, (HL)"); break;
        case 0x8f: sprintf(decode, "ADC A, A"); break;
        case 0x90: sprintf(decode, "SUB B"); break;
        case 0x91: sprintf(decode, "SUB C"); break;
        case 0x92: sprintf(decode, "SUB D"); break;
        case 0x93: sprintf(decode, "SUB E"); break;
        case 0x94: sprintf(decode, "SUB H"); break;
        case 0x95: sprintf(decode, "SUB L"); break;
        case 0x96: sprintf(decode, "SUB (HL)"); break;
        case 0x97: sprintf(decode, "SUB A"); break;
        case 0x98: sprintf(decode, "SBC A, B"); break;
        case 0x99: sprintf(decode, "SBC A, C"); break;
        case 0x9a: sprintf(decode, "SBC A, D"); break;
        case 0x9b: sprintf(decode, "SBC A, E"); break;
        case 0x9c: sprintf(decode, "SBC A, H"); break;
        case 0x9d: sprintf(decode, "SBC A, L"); break;
        case 0x9e: sprintf(decode, "SBC A, (HL)"); break;
        case 0x9f: sprintf(decode, "SBC A, A"); break;
        case 0xa0: sprintf(decode, "AND B"); break;
        case 0xa1: sprintf(decode, "AND C"); break;
        case 0xa2: sprintf(decode, "AND D"); break;
        case 0xa3: sprintf(decode, "AND E"); break;
        case 0xa4: sprintf(decode, "AND H"); break;
        case 0xa5: sprintf(decode, "AND L"); break;
        case 0xa6: sprintf(decode, "AND (HL)"); break;
        case 0xa7: sprintf(decode, "AND A"); break;
        case 0xa8: sprintf(decode, "XOR B"); break;
        case 0xa9: sprintf(decode, "XOR C"); break;
        case 0xaa: sprintf(decode, "XOR D"); break;
        case 0xab: sprintf(decode, "XOR E"); break;
        case 0xac: sprintf(decode, "XOR H"); break;
        case 0xad: sprintf(decode, "XOR L"); break;
        case 0xae: sprintf(decode, "XOR (HL)"); break;
        case 0xaf: sprintf(decode, "XOR A"); break;
        case 0xb0: sprintf(decode, "OR B"); break;
        case 0xb1: sprintf(decode, "OR C"); break;
        case 0xb2: sprintf(decode, "OR D"); break;
        case 0xb3: sprintf(decode, "OR E"); break;
        case 0xb4: sprintf(decode, "OR H"); break;
        case 0xb5: sprintf(decode, "OR L"); break;
        case 0xb6: sprintf(decode, "OR (HL)"); break;
        case 0xb7: sprintf(decode, "OR A"); break;
        case 0xb8: sprintf(decode, "CP B"); break;
        case 0xb9: sprintf(decode, "CP C"); break;
        case 0xba: sprintf(decode, "CP D"); break;
        case 0xbb: sprintf(decode, "CP E"); break;
        case 0xbc: sprintf(decode, "CP H"); break;
        case 0xbd: sprintf(decode, "CP L"); break;
        case 0xbe: sprintf(decode, "CP (HL)"); break;
        case 0xbf: sprintf(decode, "CP A"); break;
        case 0xc0: sprintf(decode, "RET NZ"); break;
        case 0xc1: sprintf(decode, "POP BC"); break;
        case 0xc2: sprintf(decode, "JP NZ, $%02x%02x", code[2], code[1]); opbytes = 3; break;
        case 0xc3: sprintf(decode, "JP $%02x%02x", code[2], code[1]); opbytes = 3; break;
        case 0xc4: sprintf(decode, "CALL NZ, $%02x%02x", code[2], code[1]); opbytes = 3; break;
        case 0xc5: sprintf(decode, "PUSH BC"); break;
        case 0xc6: sprintf(decode, "ADD A, #$%02x", code[1]); opbytes = 2; break;
        case 0xc7: sprintf(decode, "RST 00H"); break;
        case 0xc8: sprintf(decode, "RET Z"); break;
        case 0xc9: sprintf(decode, "RET"); break;
        case 0xca: sprintf(decode, "JP Z, $%02x%02x", code[2], code[1]); opbytes = 3; break;
        case 0xcb: sprintf(decode, "PREFIX CB"); break;
        case 0xcc: sprintf(decode, "CALL Z, %02x%02x", code[2], code[1]); opbytes = 3; break;
        case 0xcd: sprintf(decode, "CALL %02x%02x", code[2], code[1]); opbytes = 3; break;
        case 0xce: sprintf(decode, "ADC A, #$%02x", code[1]); opbytes = 2; break;
        case 0xcf: sprintf(decode, "RST 08H"); break;
        case 0xd0: sprintf(decode, "RET NC"); break;
        case 0xd1: sprintf(decode, "POP DE"); break;
        case 0xd2: sprintf(decode, "JP NC, $%02x%02x", code[2], code[1]); opbytes = 3; break;
        case 0xd3: sprintf(decode, ""); break;
        case 0xd4: sprintf(decode, "CALL NC, $%02x%02x", code[2], code[1]); opbytes = 3; break;
        case 0xd5: sprintf(decode, "PUSH DE"); break;
        case 0xd6: sprintf(decode, "SUB #$%02x", code[1]); opbytes = 2; break;
        case 0xd7: sprintf(decode, "RST 10H"); break;
        case 0xd8: sprintf(decode, "RET C"); break;
        case 0xd9: sprintf(decode, "RETI"); break;
        case 0xda: sprintf(decode, "JP C, $%02x%02x", code[2], code[1]); opbytes = 3; break;
        case 0xdb: sprintf(decode, ""); break;
        case 0xdc: sprintf(decode, "CALL C, $%02x%02x", code[2], code[1]); opbytes = 3; break;
        case 0xdd: sprintf(decode, ""); break;
        case 0xde: sprintf(decode, "SBC A, #$%02x", code[1]); opbytes = 2; break;
        case 0xdf: sprintf(decode, "RST 18H"); break;
        case 0xe0: sprintf(decode, "LDH $%02x, A", code[1]); opbytes = 2; break;
        case 0xe1: sprintf(decode, "POP HL"); break;
        case 0xe2: sprintf(decode, "LD (C), A"); break;
        case 0xe3: sprintf(decode, ""); break;
        case 0xe4: sprintf(decode, ""); break;
        case 0xe5: sprintf(decode, "PUSH HL"); break;
        case 0xe6: sprintf(decode, "AND #$%02x", code[1]); opbytes = 2; break;
        case 0xe7: sprintf(decode, "RST 20H"); break;
        case 0xe8: sprintf(decode, "ADD SP, $%02x", code[1]); opbytes = 2; break;
        case 0xe9: sprintf(decode, "JP (HL)"); break;
        case 0xea: sprintf(decode, "LD $%02x%02x", code[2], code[1]); opbytes = 3; break;
        case 0xeb: sprintf(decode, ""); break;
        case 0xec: sprintf(decode, ""); break;
        case 0xed: sprintf(decode, ""); break;
        case 0xee: sprintf(decode, "XOR #$%02x", code[1]); opbytes = 2; break;
        case 0xef: sprintf(decode, "RST 28H"); break;
        case 0xf0: sprintf(decode, "LDH A, $%02x", code[1]); opbytes = 2; break;
        case 0xf1: sprintf(decode, "POP AF"); break;
        case 0xf2: sprintf(decode, "LD A, (C)"); break;
        case 0xf3: sprintf(decode, "DI"); break;
        case 0xf4: sprintf(decode, ""); break;
        case 0xf5: sprintf(decode, "PUSH AF"); break;
        case 0xf6: sprintf(decode, "OR #$%02x"); opbytes = 2; break;
        case 0xf7: sprintf(decode, "RST 30H"); break;
        case 0xf8: sprintf(decode, "LD HL, SP+$%02x", code[1]); opbytes = 2; break;
        case 0xf9: sprintf(decode, "LD SP, HL"); break;
        case 0xfa: sprintf(decode, "LD A, $%02x%02x", code[2], code[1]); opbytes = 3; break;
        case 0xfb: sprintf(decode, "EI"); break;
        case 0xfc: sprintf(decode, ""); break;
        case 0xfd: sprintf(decode, ""); break;
        case 0xfe: sprintf(decode, "CP #$%02x", code[1]); opbytes = 2; break;
        case 0xff: sprintf(decode, "RST 38H"); break;
    }
    fputs(decode, file);
    fputs("\n", file);  
    return opbytes;  
}

int main(int argc, char** argv) {
    FILE *readfile = fopen(argv[1], "rb");
    FILE *writefile = fopen(argv[2], "w+"); 
    if (readfile==NULL) {    
        printf("Error: couldn't open %s\n", argv[1]);    
        exit(1);    
    }    
    fseek(readfile, 0L, SEEK_END);    
    int fsize = ftell(readfile);    
    fseek(readfile, 0L, SEEK_SET);  

    unsigned char *buffer=malloc(fsize);    
    fread(buffer, fsize, 1, readfile);
    fclose(readfile);
    int pc = 0;
    while (pc < fsize) {
        pc += DisassembleSM83Op(buffer, pc, writefile);   
    }
    fclose(writefile);
    return 0;    
}
